version: '3'
services: 
  db: 
    image: mongo:3.4
  backend:
    image: node:8.1
    volumes: 
      - ./backend:/backend
    ports:
      - 3003:3003
    command: bash -c "cd /backend && npm i && npm run production"
